# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.0"

boxes = [
    {
      :name => "master01.linux.io",
        :eth1 => "192.168.124.201",
        :mem => "2048",
        :cpu => "2"
    },
    {
      :name => "node01.linux.io",
        :eth1 => "192.168.124.101",
        :mem => "6144",
        :cpu => "2"
    },
    {
      :name => "node02.linux.io",
        :eth1 => "192.168.124.102",
        :mem => "6144",
        :cpu => "2"
    }


]

Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"

  boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.hostname = opts[:name]
        config.vm.provider "vmware_fusion" do |v|
          v.vmx["memsize"] = opts[:mem]
          v.vmx["numvcpus"] = opts[:cpu]
        end

        config.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--memory", opts[:mem]]
          v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
        end

        config.vm.network :public_network, ip: opts[:eth1]
      end
  end

  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", privileged: true, path: "./setup.sh"

end
